/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.integrador4a.igu;

/**
 *
 * @author Santiago
 */
public class MenuAdmin extends javax.swing.JFrame {

    /**
     * Creates new form MenuAdmin
     */
    public MenuAdmin() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblPanelAdmin = new javax.swing.JLabel();
        lblSolicitudes = new javax.swing.JLabel();
        lblTxtSolicitudes = new javax.swing.JLabel();
        lblSancionar = new javax.swing.JLabel();
        lblTxtSancionar = new javax.swing.JLabel();
        lblUsuarios = new javax.swing.JLabel();
        lblTxtUsuarios = new javax.swing.JLabel();
        lblDevoluciones = new javax.swing.JLabel();
        lblGestionDevoluciones = new javax.swing.JLabel();
        lblGestionSanciones = new javax.swing.JLabel();
        lblTxtSanciones = new javax.swing.JLabel();
        lblSalir = new javax.swing.JLabel();
        lblTxtSalir = new javax.swing.JLabel();
        lblFondoAdmin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPanelAdmin.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblPanelAdmin.setText("PANEL ADMINISTRADOR");
        jPanel1.add(lblPanelAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, -1, -1));

        lblSolicitudes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/solicitudUsu.png"))); // NOI18N
        lblSolicitudes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSolicitudesMouseClicked(evt);
            }
        });
        jPanel1.add(lblSolicitudes, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 140, 140));

        lblTxtSolicitudes.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTxtSolicitudes.setText("GESTIONAR SOLICITUDES");
        jPanel1.add(lblTxtSolicitudes, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, -1, -1));

        lblSancionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sancionAdmin.png"))); // NOI18N
        lblSancionar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSancionarMouseClicked(evt);
            }
        });
        jPanel1.add(lblSancionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 190, 130, 140));

        lblTxtSancionar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTxtSancionar.setText("SANCIONAR");
        jPanel1.add(lblTxtSancionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 340, -1, -1));

        lblUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/gestionAdmin.png"))); // NOI18N
        lblUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblUsuariosMouseClicked(evt);
            }
        });
        jPanel1.add(lblUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 170, 130, 160));

        lblTxtUsuarios.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTxtUsuarios.setText("GESTIONAR USUARIOS");
        jPanel1.add(lblTxtUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 340, -1, -1));

        lblDevoluciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/devolucionUsu.png"))); // NOI18N
        lblDevoluciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDevolucionesMouseClicked(evt);
            }
        });
        jPanel1.add(lblDevoluciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 420, 140, 150));

        lblGestionDevoluciones.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblGestionDevoluciones.setText("GESTION DEVOLUCIONES");
        jPanel1.add(lblGestionDevoluciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 570, -1, -1));

        lblGestionSanciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sancion2admin.png"))); // NOI18N
        lblGestionSanciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblGestionSancionesMouseClicked(evt);
            }
        });
        jPanel1.add(lblGestionSanciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 420, 130, 150));

        lblTxtSanciones.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTxtSanciones.setText("GESTIONAR SANCIONES");
        jPanel1.add(lblTxtSanciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 570, 250, 30));

        lblSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/salidaUsu.png"))); // NOI18N
        lblSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSalirMouseClicked(evt);
            }
        });
        jPanel1.add(lblSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 450, 130, 130));

        lblTxtSalir.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTxtSalir.setText("CERRAR SESION");
        jPanel1.add(lblTxtSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 590, -1, -1));

        lblFondoAdmin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblFondoAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondoAdmin.jpg"))); // NOI18N
        jPanel1.add(lblFondoAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 660));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSalirMouseClicked
        // TODO add your handling code here:
        
        //Para salir a la interfaz de Login
        Login Salir = new Login();
        Salir.setVisible(true);
        dispose();
    }//GEN-LAST:event_lblSalirMouseClicked

    private void lblSolicitudesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSolicitudesMouseClicked
        // TODO add your handling code here:
        
        //para ir a gestion de solicitudes 
        GestionarSolicitudes irSolicitud = new GestionarSolicitudes();
        irSolicitud.setVisible(true);
        dispose();
    }//GEN-LAST:event_lblSolicitudesMouseClicked

    private void lblSancionarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSancionarMouseClicked
        // TODO add your handling code here:
        
        //Para ir a sancionar
        RealizarSancion irSancion = new RealizarSancion();
        irSancion.setVisible(true);
        dispose();
    }//GEN-LAST:event_lblSancionarMouseClicked

    private void lblUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsuariosMouseClicked
        // TODO add your handling code here:
        
        //Para ir a gestion de usuarios
        GestionarUsuarios irUsuario = new GestionarUsuarios();
        irUsuario.setVisible(true);
        dispose();
    }//GEN-LAST:event_lblUsuariosMouseClicked

    private void lblDevolucionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDevolucionesMouseClicked
        // TODO add your handling code here:
        
        //Para ir a gestion de devoluciones 
        GestionarDevoluciones irGestDevolucion = new GestionarDevoluciones();
        irGestDevolucion.setVisible(true);
        dispose();
    }//GEN-LAST:event_lblDevolucionesMouseClicked

    private void lblGestionSancionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGestionSancionesMouseClicked
        // TODO add your handling code here:
        
        //Para ir a la gestion de las sanciones Gestionar Sanciones
        
        GestionarSanciones irGestSancion = new GestionarSanciones();
        irGestSancion.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_lblGestionSancionesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDevoluciones;
    private javax.swing.JLabel lblFondoAdmin;
    private javax.swing.JLabel lblGestionDevoluciones;
    private javax.swing.JLabel lblGestionSanciones;
    private javax.swing.JLabel lblPanelAdmin;
    private javax.swing.JLabel lblSalir;
    private javax.swing.JLabel lblSancionar;
    private javax.swing.JLabel lblSolicitudes;
    private javax.swing.JLabel lblTxtSalir;
    private javax.swing.JLabel lblTxtSancionar;
    private javax.swing.JLabel lblTxtSanciones;
    private javax.swing.JLabel lblTxtSolicitudes;
    private javax.swing.JLabel lblTxtUsuarios;
    private javax.swing.JLabel lblUsuarios;
    // End of variables declaration//GEN-END:variables
}
