/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.integrador4a.igu;

/**
 *
 * @author Santiago
 */
public class RealizarSolicitud extends javax.swing.JFrame {

    /**
     * Creates new form SolicitudPrestamo
     */
    public RealizarSolicitud() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblSolicitarPrestamo = new javax.swing.JLabel();
        lblFechaInicio = new javax.swing.JLabel();
        txtFechaInicio = new javax.swing.JTextField();
        lblHoraInicio = new javax.swing.JLabel();
        txtHoraInicio = new javax.swing.JTextField();
        lblHoraFin = new javax.swing.JLabel();
        txtHoraFin = new javax.swing.JTextField();
        lblFechaFin = new javax.swing.JLabel();
        txtFechaFin = new javax.swing.JTextField();
        btnEnviar = new javax.swing.JButton();
        btnMenuPrincipal = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        lblPrestarAudiio = new javax.swing.JLabel();
        lblPrestarSala = new javax.swing.JLabel();
        lblTextAudio = new javax.swing.JLabel();
        lblTextSala = new javax.swing.JLabel();
        lblFondoSolicitud = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSolicitarPrestamo.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblSolicitarPrestamo.setForeground(new java.awt.Color(255, 255, 255));
        lblSolicitarPrestamo.setText("SOLICITAR PRESTAMO");
        jPanel1.add(lblSolicitarPrestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 550, 60));

        lblFechaInicio.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblFechaInicio.setForeground(new java.awt.Color(255, 255, 255));
        lblFechaInicio.setText("Fecha Inicio:");
        jPanel1.add(lblFechaInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 150, 40));
        jPanel1.add(txtFechaInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 230, 30));

        lblHoraInicio.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblHoraInicio.setForeground(new java.awt.Color(255, 255, 255));
        lblHoraInicio.setText("Hora Inicio:");
        jPanel1.add(lblHoraInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 150, 40));
        jPanel1.add(txtHoraInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, 230, 30));

        lblHoraFin.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblHoraFin.setForeground(new java.awt.Color(255, 255, 255));
        lblHoraFin.setText("Hora Fin:");
        jPanel1.add(lblHoraFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, 150, 40));
        jPanel1.add(txtHoraFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, 230, 30));

        lblFechaFin.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblFechaFin.setForeground(new java.awt.Color(255, 255, 255));
        lblFechaFin.setText("Fecha Fin:");
        jPanel1.add(lblFechaFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 440, 150, 40));
        jPanel1.add(txtFechaFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 480, 230, 30));

        btnEnviar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEnviar.setText("ENVIAR");
        jPanel1.add(btnEnviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 560, 130, 40));

        btnMenuPrincipal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMenuPrincipal.setText("MENU PRINCIPAL");
        btnMenuPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuPrincipalActionPerformed(evt);
            }
        });
        jPanel1.add(btnMenuPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 560, 160, 40));

        btnSalir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 560, 130, 40));

        lblPrestarAudiio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/audiovisualUsu.png"))); // NOI18N
        lblPrestarAudiio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPrestarAudiioMouseClicked(evt);
            }
        });
        jPanel1.add(lblPrestarAudiio, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 260, 150, 150));

        lblPrestarSala.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/SalaUsu.png"))); // NOI18N
        lblPrestarSala.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPrestarSalaMouseClicked(evt);
            }
        });
        jPanel1.add(lblPrestarSala, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 270, 180, 130));

        lblTextAudio.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTextAudio.setForeground(new java.awt.Color(255, 255, 255));
        lblTextAudio.setText("PRESTAMO AUDIOVISUAL");
        jPanel1.add(lblTextAudio, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 420, -1, -1));

        lblTextSala.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTextSala.setForeground(new java.awt.Color(255, 255, 255));
        lblTextSala.setText("PRESTAMO SALA");
        jPanel1.add(lblTextSala, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 420, -1, -1));

        lblFondoSolicitud.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/FondoUsu.jpg"))); // NOI18N
        jPanel1.add(lblFondoSolicitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 660));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuPrincipalActionPerformed
        // TODO add your handling code here:
        
        //Ir a la interfaz del menu principla(MenuUsuario)
        MenuUsuario irMenu = new MenuUsuario();
        irMenu.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnMenuPrincipalActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        
        //Ir a la interfaz de inicial de LOGIN
        Login irInicio = new Login();
        irInicio.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void lblPrestarAudiioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPrestarAudiioMouseClicked
        // TODO add your handling code here:

        //Para ir a la interfaz de Prestar Audiovisual
        PrestamoAudio IrAudio = new PrestamoAudio();
        IrAudio.setVisible(true);
        dispose();
    }//GEN-LAST:event_lblPrestarAudiioMouseClicked

    private void lblPrestarSalaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPrestarSalaMouseClicked
        // TODO add your handling code here:

        //Para ir a la interfaz de Prestar Sala
        PrestamoSala IrSala = new PrestamoSala();
        IrSala.setVisible(true);
        dispose();
    }//GEN-LAST:event_lblPrestarSalaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RealizarSolicitud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RealizarSolicitud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RealizarSolicitud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RealizarSolicitud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RealizarSolicitud().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviar;
    private javax.swing.JButton btnMenuPrincipal;
    private javax.swing.JButton btnSalir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblFechaFin;
    private javax.swing.JLabel lblFechaInicio;
    private javax.swing.JLabel lblFondoSolicitud;
    private javax.swing.JLabel lblHoraFin;
    private javax.swing.JLabel lblHoraInicio;
    private javax.swing.JLabel lblPrestarAudiio;
    private javax.swing.JLabel lblPrestarSala;
    private javax.swing.JLabel lblSolicitarPrestamo;
    private javax.swing.JLabel lblTextAudio;
    private javax.swing.JLabel lblTextSala;
    private javax.swing.JTextField txtFechaFin;
    private javax.swing.JTextField txtFechaInicio;
    private javax.swing.JTextField txtHoraFin;
    private javax.swing.JTextField txtHoraInicio;
    // End of variables declaration//GEN-END:variables
}
