/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.integrador4a.igu;

/**
 *
 * @author Santiago
 */
public class PrestamoAudio extends javax.swing.JFrame {

    /**
     * Creates new form PrestamoAudio
     */
    public PrestamoAudio() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblPrestamosAudio = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblTipo = new javax.swing.JLabel();
        txtTipo = new javax.swing.JTextField();
        lblEstado = new javax.swing.JLabel();
        txtEstado = new javax.swing.JTextField();
        btnEnviar = new javax.swing.JButton();
        btnMenuPrincipal = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        lblAudiovisual1 = new javax.swing.JLabel();
        lblAudiovisual2 = new javax.swing.JLabel();
        lblAudiovisual3 = new javax.swing.JLabel();
        btnIrSala = new javax.swing.JButton();
        lblFondoAudio = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPrestamosAudio.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblPrestamosAudio.setForeground(new java.awt.Color(255, 255, 255));
        lblPrestamosAudio.setText("PRESTAMO DE AUDIOVISUALES");
        jPanel1.add(lblPrestamosAudio, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, -1, -1));

        lblNombre.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre.setText("Nombre:");
        jPanel1.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 150, 30));
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 250, 30));

        lblTipo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTipo.setForeground(new java.awt.Color(255, 255, 255));
        lblTipo.setText("Tipo:");
        jPanel1.add(lblTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 210, 30));
        jPanel1.add(txtTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, 250, 30));

        lblEstado.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblEstado.setForeground(new java.awt.Color(255, 255, 255));
        lblEstado.setText("Estado:");
        jPanel1.add(lblEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 470, 130, 20));
        jPanel1.add(txtEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 510, 250, 30));

        btnEnviar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEnviar.setText("ENVIAR");
        jPanel1.add(btnEnviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 570, 130, 40));

        btnMenuPrincipal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMenuPrincipal.setText("MENU PRINCIPAL");
        btnMenuPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuPrincipalActionPerformed(evt);
            }
        });
        jPanel1.add(btnMenuPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 570, 170, 40));

        btnSalir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 570, 110, 40));

        lblAudiovisual1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Santiago\\Desktop\\portatilUsu.png")); // NOI18N
        jPanel1.add(lblAudiovisual1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 220, 130, 150));

        lblAudiovisual2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Santiago\\Desktop\\proyectorUsu.png")); // NOI18N
        jPanel1.add(lblAudiovisual2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 330, 180, 130));

        lblAudiovisual3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Santiago\\Desktop\\camaraUsu.png")); // NOI18N
        jPanel1.add(lblAudiovisual3, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 340, 160, 130));

        btnIrSala.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnIrSala.setText("SALA");
        btnIrSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIrSalaActionPerformed(evt);
            }
        });
        jPanel1.add(btnIrSala, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 570, 170, 40));

        lblFondoAudio.setForeground(new java.awt.Color(255, 255, 255));
        lblFondoAudio.setIcon(new javax.swing.ImageIcon("C:\\Users\\Santiago\\Desktop\\FondoUsu.jpg")); // NOI18N
        jPanel1.add(lblFondoAudio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 660));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuPrincipalActionPerformed
        // TODO add your handling code here:
        
        //Ir al menu principal del usuario(PANEL USUARIO)
        MenuUsuario irPrincipal = new MenuUsuario();
        irPrincipal.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnMenuPrincipalActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        
        //SALIR DE LA INTERFAZ AL INICIO(LOGIN)
        Login irInicio = new Login();
        irInicio.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnIrSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIrSalaActionPerformed
        // TODO add your handling code here:
        
        //ir a prestamo de sala 
        PrestamoSala irSala = new PrestamoSala();
        irSala.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnIrSalaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrestamoAudio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrestamoAudio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrestamoAudio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrestamoAudio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrestamoAudio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviar;
    private javax.swing.JButton btnIrSala;
    private javax.swing.JButton btnMenuPrincipal;
    private javax.swing.JButton btnSalir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAudiovisual1;
    private javax.swing.JLabel lblAudiovisual2;
    private javax.swing.JLabel lblAudiovisual3;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblFondoAudio;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPrestamosAudio;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTipo;
    // End of variables declaration//GEN-END:variables
}
